### PR TITLE
New primary estimate cols

### PR DESCRIPTION
**Pull request by rahularoradfs**
## Briefly describe the feature or bug that this PR addresses.

Modifies `airtable_fields_config` to draw from the new relevant Airtable variable names. 

Also, adds documentation for how to dump and restore the db using native `psql` functionality. 

## Please link the Airtable ticket associated with this PR.

None.

## Describe the steps you took to test the feature/bugfix introduced by this PR.

Ran ETL locally.

## Does any infrastructure work need to be done before this PR can be pushed to production?

No.

### CODE REVIEW

**Comment by rahularoradfs** [comment]
@atatmaja, @simonarocco -- is there a good reason that we are using CSVs for db dumps? I found a native psql solution - documented in README
- https://www.postgresql.org/docs/9.6/app-pgdump.html

This solution seems especially interesting because it would let us sync to and from remote DBs (i.e., could sync local and prod -- either prod to local or local to prod) 
- https://axiomq.com/blog/backup-and-restore-a-postgresql-database/

**Comment by atatmaja** [comment]
> @atatmaja, @simonarocco -- is there a good reason that we are using CSVs for db dumps? I found a native psql solution - documented in README
> 
> * https://www.postgresql.org/docs/9.6/app-pgdump.html
> 
> This solution seems especially interesting because it would let us sync to and from remote DBs (i.e., could sync local and prod -- either prod to local or local to prod)
> 
> * https://axiomq.com/blog/backup-and-restore-a-postgresql-database/
@rahularoradfs csvs were more of a quick and dirty solution (because we already had code to create create csv esque representations of tables). I'm open to finding a better solution if we see ourselves needing to do more db dumps in the future

**Comment by rahularoradfs** [comment]
@atatmaja possibly, yes -- e.g., revamping test adjustment -> will run locally then upload

**Review by simonarocco — APPROVED** [review]
lgtm, thanks for the extra documentation

**Pull request merged**
